<script setup>
import { computed, ref, watch } from 'vue'

import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import Message from 'primevue/message'
import ProgressSpinner from 'primevue/progressspinner'

import { api } from '@/api'
import logoUrl from '@/assets/ultra-trace-logo.png'
import {
  COMPANY_URL,
  REPOSITORY_URL,
  SECURITY_POLICY_URL,
  builtVersion,
  combineNotices,
  copyrightNotice,
  legalLinks,
  linkTarget,
  releaseNotesUrl,
  supportLabel,
  versionReport,
  versionsDiffer
} from '@/lib/about'
import { copyText } from '@/lib/clipboard'

import { useSidebarMenu } from './state.js'

// The home menu's About tab: which build is running - copyable, since that is
// the first thing a support request needs - who makes the product and under
// which licence, and where the documentation, legal documents and support
// live. The licence and notices open in place rather than linking out: the app
// is air-gapped by design, and a reviewer must be able to read them without
// leaving it.

const sidebarMenu = useSidebarMenu()
const open = computed(() => sidebarMenu.open && sidebarMenu.tab === 'about')

const version = builtVersion()
const serverVersion = ref(null)
const copyState = ref(null) // null | 'copied' | 'failed'
const links = legalLinks()
const pane = ref()

// The server's build is read only to catch the rare mismatch - a tab left open
// across an update, or one container not restarted. A deployment's two images
// otherwise always carry the same version, so one line is shown, and a server
// that cannot be read simply leaves the warning out.
const drift = computed(() => versionsDiffer(version, serverVersion.value))

const loadServerVersion = async () => {
  serverVersion.value = null
  try {
    const data = await api.http.get('/version', {
      use: 'read',
      type: 'version',
      errors: 'inline'
    })
    serverVersion.value = data?.version ?? null
  } catch {
    serverVersion.value = null
  }
}

// Re-read each time the tab is shown: the server can be updated underneath an
// open tab, which is exactly the mismatch the warning is there for.
watch(
  open,
  (shown) => {
    if (!shown) return
    copyState.value = null
    loadServerVersion()
  },
  { immediate: true }
)

const copyLabel = computed(
  () => ({ copied: 'Copied', failed: 'Copy failed' })[copyState.value] ?? 'Copy version details'
)

const copyVersions = async () => {
  const report = versionReport({ web: version, server: serverVersion.value })
  copyState.value = (await copyText(report, pane.value)) ? 'copied' : 'failed'
}

// --- Documents, rendered in place ---

const fetchText = async (url) => {
  const response = await fetch(url, { cache: 'no-cache' })
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`)
  return response.text()
}

const serverNotices = async () =>
  (
    await api.http.get('/version/third-party-notices', {
      responseType: 'text',
      type: 'third_party_notices',
      errors: 'inline'
    })
  ).data

// A third-party list that cannot be read is replaced by a line saying why, so
// NOTICE and the other list still show. A source checkout has neither: the
// npm list needs a production build, the Python one an image build.
const orExplain = (load, explanation) => load().catch(() => explanation)

const DOCUMENTS = {
  license: { title: 'Apache License 2.0', load: () => fetchText('/legal/LICENSE.txt') },
  notices: {
    title: 'Notices',
    load: async () =>
      combineNotices(
        await Promise.all([
          fetchText('/legal/NOTICE.txt'),
          orExplain(
            () => fetchText('/legal/THIRD_PARTY_NOTICES.txt'),
            'Mascope web app - third-party notices\n\n' +
              'Not available: they are generated by a production build of the web app.'
          ),
          orExplain(
            serverNotices,
            'Mascope server - third-party notices\n\n' +
              'Not available: this server has none. They are generated when its image is built.'
          )
        ])
      )
  }
}

const documentOpen = ref(false)
const shown = ref({ title: '', text: '', loading: false, error: null })
let request = 0

const openDocument = async (key) => {
  const { title, load } = DOCUMENTS[key]
  const current = ++request
  shown.value = { title, text: '', loading: true, error: null }
  documentOpen.value = true
  try {
    const text = await load()
    if (current === request) shown.value = { ...shown.value, text, loading: false }
  } catch {
    if (current === request) {
      shown.value = { ...shown.value, loading: false, error: 'This document could not be loaded.' }
    }
  }
}
</script>

<template>
  <div ref="pane" class="about">
    <h2>About</h2>
    <div class="brand">
      <img :src="logoUrl" alt="Ultra Trace" class="wordmark" />
      <b>Mascope</b>
    </div>

    <section aria-labelledby="about-version-heading">
      <h3 id="about-version-heading">Version</h3>
      <p class="version">{{ version ?? 'unknown' }}</p>
      <Message v-if="drift" severity="warn" size="small">
        The server is running {{ serverVersion }}, but this page was loaded from {{ version }}.
        Reload the page; if that does not clear it, the web app and the server are running different
        builds.
      </Message>
      <div class="actions">
        <Button
          :label="copyLabel"
          :icon="copyState === 'copied' ? 'pi pi-check' : 'pi pi-clone'"
          size="small"
          severity="secondary"
          @click="copyVersions"
        />
        <Button
          as="a"
          :href="releaseNotesUrl(version)"
          target="_blank"
          rel="noopener noreferrer"
          label="Release notes"
          icon="pi pi-external-link"
          size="small"
          severity="secondary"
          text
        />
      </div>
    </section>

    <section aria-labelledby="about-legal-heading">
      <h3 id="about-legal-heading">Legal</h3>
      <p>
        {{ copyrightNotice }}. Mascope is open-source software licensed under the Apache License
        2.0; its source is published at
        <a :href="REPOSITORY_URL" target="_blank" rel="noopener noreferrer"
          >github.com/ultra-trace-systems/mascope</a
        >.
      </p>
      <div class="actions">
        <Button
          label="Apache License 2.0"
          size="small"
          severity="secondary"
          text
          @click="openDocument('license')"
        />
        <Button
          label="Notices"
          size="small"
          severity="secondary"
          text
          @click="openDocument('notices')"
        />
      </div>
    </section>

    <section aria-labelledby="about-links-heading">
      <h3 id="about-links-heading">Links</h3>
      <ul class="links">
        <li>
          <a :href="COMPANY_URL" target="_blank" rel="noopener noreferrer">ultratrace.eu</a>
        </li>
        <li><a href="/docs/" target="_blank" rel="noopener">User documentation</a></li>
        <li v-if="links.support">
          Support:
          <a :href="links.support" :target="linkTarget(links.support)" rel="noopener noreferrer">{{
            supportLabel(links.support)
          }}</a>
        </li>
        <li v-if="links.privacy">
          <a :href="links.privacy" :target="linkTarget(links.privacy)" rel="noopener noreferrer"
            >Privacy notice</a
          >
        </li>
        <li v-if="links.terms">
          <a :href="links.terms" :target="linkTarget(links.terms)" rel="noopener noreferrer"
            >Terms of service</a
          >
        </li>
        <li>
          <a :href="SECURITY_POLICY_URL" target="_blank" rel="noopener noreferrer"
            >Security policy</a
          >
        </li>
      </ul>
    </section>

    <Dialog
      v-model:visible="documentOpen"
      :header="shown.title"
      modal
      :draggable="false"
      :style="{ width: 'min(60rem, 95vw)' }"
    >
      <ProgressSpinner v-if="shown.loading" />
      <Message v-else-if="shown.error" severity="warn">{{ shown.error }}</Message>
      <pre v-else class="legal-text">{{ shown.text }}</pre>
    </Dialog>
  </div>
</template>

<style scoped>
.about {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

h2,
h3 {
  margin: 0;
}

h3 {
  margin-bottom: 0.5rem;
  opacity: 0.7;
}

.brand {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 15px;
}

.wordmark {
  height: 24px;
  display: block;
}

p {
  margin: 0;
  line-height: 1.5;
}

.version {
  font-family: 'IBM Plex Mono', monospace;
  user-select: all;
  margin-bottom: 0.5rem;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-top: 0.5rem;
}

.links {
  margin: 0;
  padding-left: 1.25rem;
  line-height: 1.7;
}

.legal-text {
  margin: 0;
  max-height: 70vh;
  overflow: auto;
  white-space: pre-wrap;
  font-size: 0.8rem;
}
</style>
