[project]
name = "mascope_file"
version = "0.0.0"
description = "Mascope's internal file library"
authors = [{ name = "Oskari Kausiala", email = "oskari.kausiala@ultratrace.eu" }]
requires-python = ">=3.12,<3.13"
dependencies = [
    "mascope_runtime",
    "datetime-glob~=1.0",
    "numpy~=2.5",
    "xarray>=2026.7.0",
    "zarr",
    "numcodecs==0.15.1", # TODO: See issue above 
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"
