"""
Integration tests for auth and size limits on the TUS upload endpoint.

Agents (File Agent) authenticate with a service access token. The TUS
routes are generated by tuspyserver, so they cannot take the @api_route
decorator; sample_files_routes stamps their endpoints `token_access`
instead. These tests pin that stamp down: a file-agent token must pass
the auth layer on every tus route (creation, chunk transfer, HEAD,
OPTIONS, DELETE), while the service-name check and anonymous rejection
keep working - including that an anonymous PATCH is refused before its
body is written. They also pin the per-upload size cap: OPTIONS advertises
it as Tus-Max-Size, a creation declaring a larger Upload-Length is refused
with 413, and a deferred-length creation is refused with 411.

The upload is never completed here (chunks stop short of Upload-Length),
so the file-processing pipeline behind the completion hook stays out of
scope.
"""

import base64

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy import delete

from mascope_backend.api.routes.sample.files import sample_files_routes
from mascope_backend.app.fast import fast
from mascope_backend.db import AccessToken


TUS_URL = "/api/sample/files/upload/tus/"


def _b64(value: str) -> str:
    return base64.b64encode(value.encode()).decode()


CREATE_HEADERS = {
    "Tus-Resumable": "1.0.0",
    "Upload-Length": "8",
    "Upload-Metadata": (
        f"filename {_b64('orbi1_20260801_pos.raw')},"
        f"filetype {_b64('application/octet-stream')}"
    ),
}


@pytest_asyncio.fixture
async def file_agent_token(async_session_factory, test_users):
    """A real file-agent access token row for the editor test user."""
    token = "tus-token-access-integration-test".ljust(43, "x")
    async with async_session_factory() as session:
        session.add(
            AccessToken(
                token=token,
                user_id=test_users["editor"].id,
                service_name="file-agent",
            )
        )
        await session.commit()
    yield token
    async with async_session_factory() as session:
        await session.execute(delete(AccessToken).where(AccessToken.token == token))
        await session.commit()


def _client(headers: dict | None = None) -> AsyncClient:
    return AsyncClient(
        transport=ASGITransport(app=fast), base_url="http://test", headers=headers
    )


@pytest.mark.asyncio
async def test_agent_token_can_create_and_patch_upload(file_agent_token):
    headers = {
        "Authorization": f"Bearer {file_agent_token}",
        "X-Service-Name": "file-agent",
    }
    async with _client(headers) as client:
        resp = await client.post(TUS_URL, headers=CREATE_HEADERS)
        assert resp.status_code == 201, resp.text
        upload_id = resp.headers["location"].rstrip("/").rsplit("/", 1)[-1]
        assert upload_id

        # Send half of Upload-Length: the chunk is accepted and the
        # upload stays open (no completion pipeline).
        resp = await client.patch(
            f"{TUS_URL}{upload_id}",
            content=b"half",
            headers={
                "Tus-Resumable": "1.0.0",
                "Upload-Offset": "0",
                "Content-Type": "application/offset+octet-stream",
            },
        )
        assert resp.status_code == 204, resp.text
        assert resp.headers["upload-offset"] == "4"


@pytest.mark.asyncio
async def test_token_with_mismatched_service_name_is_rejected(file_agent_token):
    headers = {
        "Authorization": f"Bearer {file_agent_token}",
        "X-Service-Name": "mascope_sdk",  # token is for file-agent
    }
    async with _client(headers) as client:
        resp = await client.post(TUS_URL, headers=CREATE_HEADERS)
    assert resp.status_code == 401


@pytest.mark.asyncio
async def test_anonymous_upload_creation_is_rejected():
    async with _client() as client:
        resp = await client.post(TUS_URL, headers=CREATE_HEADERS)
    assert resp.status_code == 401


@pytest.mark.asyncio
async def test_anonymous_head_options_delete_are_rejected():
    """The generated metadata routes require auth like creation and chunks.

    Auth resolves before the handler, so even a nonexistent upload id
    answers 401 (not 404) to an anonymous caller.
    """
    async with _client() as client:
        head = await client.head(f"{TUS_URL}no-such-upload")
        options = await client.options(TUS_URL)
        terminate = await client.delete(f"{TUS_URL}no-such-upload")
    assert head.status_code == 401
    assert options.status_code == 401
    assert terminate.status_code == 401


@pytest.mark.asyncio
async def test_agent_token_can_inspect_and_terminate_upload(file_agent_token):
    headers = {
        "Authorization": f"Bearer {file_agent_token}",
        "X-Service-Name": "file-agent",
    }
    async with _client(headers) as client:
        resp = await client.post(TUS_URL, headers=CREATE_HEADERS)
        assert resp.status_code == 201, resp.text
        upload_id = resp.headers["location"].rstrip("/").rsplit("/", 1)[-1]

        head = await client.head(f"{TUS_URL}{upload_id}")
        assert head.status_code == 200, head.text
        assert head.headers["upload-offset"] == "0"

        terminate = await client.delete(f"{TUS_URL}{upload_id}")
        assert terminate.status_code == 204, terminate.text

        head_after = await client.head(f"{TUS_URL}{upload_id}")
        assert head_after.status_code == 404


@pytest.mark.asyncio
async def test_options_advertises_the_configured_max_size(file_agent_token):
    headers = {
        "Authorization": f"Bearer {file_agent_token}",
        "X-Service-Name": "file-agent",
    }
    async with _client(headers) as client:
        resp = await client.options(TUS_URL)
    assert resp.status_code == 204
    # Advertise exactly the cap the server enforces (the module global the
    # router's max_size is built from), so the header can't drift from it.
    assert resp.headers["tus-max-size"] == str(
        sample_files_routes._tus_max_upload_bytes
    )


@pytest.mark.asyncio
async def test_oversized_upload_is_rejected_at_creation(file_agent_token, monkeypatch):
    """An Upload-Length beyond the cap fails fast instead of stalling later."""
    monkeypatch.setattr(sample_files_routes, "_tus_max_upload_bytes", 4)
    headers = {
        "Authorization": f"Bearer {file_agent_token}",
        "X-Service-Name": "file-agent",
    }
    async with _client(headers) as client:
        # CREATE_HEADERS declares Upload-Length: 8 > the patched 4-byte cap.
        resp = await client.post(TUS_URL, headers=CREATE_HEADERS)
    assert resp.status_code == 413


@pytest.mark.asyncio
async def test_anonymous_patch_is_rejected():
    """PATCH rejects anonymous callers before the body is written to disk.

    tuspyserver declares the chunk-writing dependency ahead of its own auth
    hook, so auth is enforced at the router level to run first. Before that,
    an anonymous PATCH would create the upload file and stream its body in,
    then answer 404; now it is 401 with nothing written.
    """
    async with _client() as client:
        resp = await client.patch(
            f"{TUS_URL}some-upload-id",
            content=b"attacker",
            headers={
                "Tus-Resumable": "1.0.0",
                "Upload-Offset": "0",
                "Content-Type": "application/offset+octet-stream",
            },
        )
    assert resp.status_code == 401, resp.text


@pytest.mark.asyncio
async def test_deferred_length_creation_is_rejected(file_agent_token):
    """A creation that omits Upload-Length (deferred) is refused with 411.

    Deferred uploads declare their size only on a later PATCH, which
    tuspyserver never re-checks against the cap, so allowing them would let a
    client bypass the per-upload limit.
    """
    headers = {
        "Authorization": f"Bearer {file_agent_token}",
        "X-Service-Name": "file-agent",
    }
    create = {
        "Tus-Resumable": "1.0.0",
        "Upload-Defer-Length": "1",
        "Upload-Metadata": CREATE_HEADERS["Upload-Metadata"],
    }
    async with _client(headers) as client:
        resp = await client.post(TUS_URL, headers=create)
    assert resp.status_code == 411, resp.text
