"""
User management service module for Mascope user management.

This module contains the `UserManager` class extending FastAPI Users' class `BaseUserManager`.
It implements core lifecycle hooks and logic for user management in the Mascope server,
including registration, password updates, token management, and custom behaviors
such as access token cleanup for external services like Jupyter.
"""

import os
from datetime import datetime, timezone
from typing import Any, Dict, Optional, Union

from fastapi import Request, Response
from fastapi_users import BaseUserManager, IntegerIDMixin, models
from fastapi_users.exceptions import InvalidPasswordException
from sqlalchemy import select

from mascope_backend.api.lib.exceptions.api_exceptions import NotFoundException
from mascope_backend.api.lib.rate_limit import clear_login_rate_limit
from mascope_backend.api.new.auth.access_token.service import regenerate_access_token
from mascope_backend.api.new.auth.config import auth_settings
from mascope_backend.api.new.users import exceptions
from mascope_backend.api.new.users.access_token.service import delete_user_access_tokens
from mascope_backend.api.new.users.schemas import UserCreate, UserRead, UserUpdate
from mascope_backend.api.new.users.user_manager.common_passwords import (
    is_common_password,
)
from mascope_backend.db import Role, User, async_session
from mascope_backend.runtime import runtime
from mascope_backend.socket.auth import (
    SocketUnauthenticatedError,
    authenticate_socket_connection,
)
from mascope_backend.socket.records.service import (
    emit_record_created,
    emit_record_deleted,
    emit_record_updated,
)


class UserManager(IntegerIDMixin, BaseUserManager[User, int]):
    """
    Responsible for managing user-related operations, including registration,
    password reset, email verification, and token management, etc.

    This class extends the FastAPI Users `BaseUserManager` and adds custom logic for handling
    user management in the Mascope server. See BaseUserManager for more examples.

    :param IntegerIDMixin: Mixin for managing users with integer-based IDs.
    :param BaseUserManager: FastAPI Users' base user manager with core user handling logic.
    :raises exceptions.UserAlreadyExists: Raised when trying to create a user that already exists.
    :return: Instance of a newly created or managed user.
    :rtype: models.UP
    """

    reset_password_token_secret = auth_settings.RESET_PASSWORD_TOKEN_SECRET
    reset_password_token_lifetime_seconds = (
        auth_settings.RESET_PASSWORD_TOKEN_LIFETIME_SECONDS
    )
    reset_password_token_audience = auth_settings.RESET_PASSWORD_TOKEN_AUDIENCE
    verification_token_secret = auth_settings.VERIFICATION_TOKEN_SECRET
    verification_token_lifetime_seconds = (
        auth_settings.VERIFICATION_TOKEN_LIFETIME_SECONDS
    )
    verification_token_audience = auth_settings.VERIFICATION_TOKEN_AUDIENCE

    # Minimum password length. Length is the single strongest lever on password
    # strength; kept simple deliberately (no forced character-class rules).
    MIN_PASSWORD_LENGTH = 12

    async def validate_password(
        self,
        password: str,
        user: Union[UserCreate, UserUpdate, User],
    ) -> None:
        """
        Enforce the password policy on registration and password change.

        FastAPI Users calls this before hashing. Raising
        ``InvalidPasswordException`` surfaces as a 400 with the given reason
        (see the handler in ``app/fast.py``).

        :param password: The candidate plaintext password.
        :param user: The user being created/updated (fields may be partial on update).
        :raises InvalidPasswordException: If the password fails the policy.
        """
        if len(password) < self.MIN_PASSWORD_LENGTH:
            raise InvalidPasswordException(
                reason=(
                    f"Password must be at least {self.MIN_PASSWORD_LENGTH} "
                    "characters long."
                )
            )

        # A password long enough to clear the length check can still be one of
        # the most-used strings in circulation ("qwerty123456",
        # "passwordpassword"). Checked after the length rule, so a short common
        # password is told the thing it can act on, and before the identifier
        # rules, since it is a set lookup rather than two substring scans.
        if is_common_password(password):
            raise InvalidPasswordException(
                reason=(
                    "This password is among the most commonly used ones. "
                    "Please choose a different one."
                )
            )

        lowered = password.lower()
        # Reject passwords that just echo the account's own identifiers. Only
        # check identifiers of a meaningful length: a 1-3 char local-part/username
        # would otherwise trigger false positives against random passwords (e.g.
        # the one generated by an admin password reset).
        min_identifier_len = 4
        email = getattr(user, "email", None)
        email_local = email.split("@")[0].lower() if email else ""
        if len(email_local) >= min_identifier_len and email_local in lowered:
            raise InvalidPasswordException(
                reason="Password must not contain your email address."
            )
        username = getattr(user, "username", None)
        if (
            username
            and len(username) >= min_identifier_len
            and username.lower() in lowered
        ):
            raise InvalidPasswordException(
                reason="Password must not contain your username."
            )

    async def get(self, id: models.ID) -> models.UP:
        """
        Get a user by id.

        :param id: Id. of the user to retrieve.
        :raises UserNotExists: The user does not exist.
        :return: A user.
        """
        user = await self.user_db.get(id)

        if user is None:
            raise NotFoundException(f"User with ID '{id}' not found")

        return user

    async def _get_user_dict_with_role(self, user: User) -> dict:
        """
        Convert User model to dict including role_name from joined Role table.

        :param user: User model instance
        :return: User dict with role_name field
        """
        async with async_session() as session:
            query = select(Role.role_name).filter(Role.role_id == user.role_id)
            result = await session.execute(query)
            role_name = result.scalar_one_or_none()
            user_data = user.to_dict()
            user_data["role_name"] = role_name

            return user_data

    async def create(
        self,
        user_create: UserCreate,
        safe: bool = False,
        request: Optional[Request] = None,
        *,
        require_password_change: bool = True,
    ) -> models.UP:
        """
        Create a user in database.

        Triggers the on_after_register handler on success.

        :param user_create: The UserCreate model to create.
        :param safe: If True, sensitive values like is_superuser or is_verified
        will be ignored during the creation, defaults to False.
        :param request: Optional FastAPI request that
        triggered the operation, defaults to None.
        :param require_password_change: Whether the new account must replace its
        password before it can use the application. True for accounts an
        administrator creates, since the administrator chose the password. The
        first-owner bootstrap passes False: that form is filled in by the
        account holder themselves.
        :raises UserAlreadyExists: A user already exists with the same e-mail.
        :return: A new user.
        """
        await self.validate_password(user_create.password, user_create)

        existing_user = await self.user_db.get_by_email(user_create.email)
        if existing_user is not None:
            raise exceptions.UserEmailAlreadyExistsException(user_create.email)

        user_dict = (
            user_create.create_update_dict()
            if safe
            else user_create.create_update_dict_superuser()
        )
        password = user_dict.pop("password")
        user_dict["hashed_password"] = self.password_helper.hash(password)
        user_dict["password_changed_at"] = datetime.now(timezone.utc)
        user_dict["must_change_password"] = require_password_change
        user_dict["password_change_reason"] = (
            "new_account" if require_password_change else None
        )

        created_user = await self.user_db.create(user_dict)

        await self.on_after_register(created_user, request)

        return created_user

    async def update(
        self,
        user_update: UserUpdate,
        user: models.UP,
        safe: bool = False,
        request: Optional[Request] = None,
    ) -> models.UP:
        """
        Update a user in database and manage file-converter token on role change.

        :param user_update: The UserUpdate model containing
        the changes to apply to the user.
        :param user: The current user to update.
        :param safe: If True, sensitive values like is_superuser or is_verified
        will be ignored during the update, defaults to False
        :param request: Optional FastAPI request that
        triggered the operation, defaults to None.
        :return: The updated user.
        """
        old_role_id = user.role_id
        # Call parent update (this triggers on_after_update)
        updated_user = await super().update(user_update, user, safe, request)

        # Handle file-converter token on role change
        if (
            hasattr(user_update, "role_id")  # UserUpdateMe does not have role_id
            and user_update.role_id is not None
            and old_role_id != updated_user.role_id
        ):
            editor_level = auth_settings.ROLE_ACCESS_LEVELS.get("editor")
            promoted_to_editor = old_role_id < editor_level <= updated_user.role_id
            demoted_to_guest = old_role_id >= editor_level > updated_user.role_id

            if promoted_to_editor:
                await regenerate_access_token(
                    user=updated_user, service_name="file-converter"
                )
                runtime.logger.info(
                    f"Generated file-converter token for {updated_user.username}"
                )
            elif demoted_to_guest:
                await delete_user_access_tokens(
                    user_id=updated_user.id, service_name="file-converter"
                )
                runtime.logger.info(
                    f"Removed file-converter token for {updated_user.username}"
                )

        return updated_user

    async def _update(self, user: models.UP, update_dict: Dict[str, Any]) -> models.UP:
        """
        Apply an update, requiring a password change whenever a password is written.

        Every password write in FastAPI Users funnels through here, and a write
        that reaches this point did not necessarily come from the account
        holder: both `UserUpdate` and the administrator reset carry a
        `password` field. Requiring a change is therefore the safe default, and
        the one path that proves the holder knew the old password clears the
        flag instead - see :meth:`set_own_password`. Anything else added later
        gets the safe behaviour without having to remember this.

        The flag rides in the same update as the hash, so the two can never
        disagree.

        :param user: The user being updated.
        :param update_dict: The fields to write; a ``password`` key is plaintext.
        :return: The updated user.
        """
        if update_dict.get("password") is None:
            return await super()._update(user, update_dict)
        return await super()._update(
            user,
            {
                **update_dict,
                "must_change_password": True,
                "password_change_reason": "reset",
                "password_changed_at": datetime.now(timezone.utc),
            },
        )

    async def set_own_password(
        self,
        user: models.UP,
        password: str,
        request: Optional[Request] = None,
    ) -> models.UP:
        """
        Store a password the account holder chose for themselves.

        The only path that clears a pending forced password change, and reached
        only from the self-service credentials route, which proves the holder
        knew the old password by authenticating them first. Deliberately does
        not go through :meth:`_update`, whose job is the opposite.

        Written as a single update and reported through ``on_after_update`` so
        token revocation and the record broadcast observe the cleared flag
        rather than a value corrected afterwards.

        :param user: The account holder.
        :param password: The new plaintext password.
        :param request: Optional FastAPI request that triggered the operation.
        :raises InvalidPasswordException: If the password fails the policy.
        :return: The updated user.
        """
        await self.validate_password(password, user)
        updated_user = await self.user_db.update(
            user,
            {
                "hashed_password": self.password_helper.hash(password),
                "must_change_password": False,
                "password_change_reason": None,
                "password_changed_at": datetime.now(timezone.utc),
            },
        )
        await self.on_after_update(updated_user, {"password": password}, request)
        return updated_user

    async def on_after_register(self, user: User, request: Optional[Request] = None):
        runtime.logger.info(f"User {user.username} was registered.")

        user_dict = await self._get_user_dict_with_role(user)
        validated_user_dict = UserRead.model_validate(user_dict).model_dump()
        await emit_record_created(
            record_type="user",
            record_id=str(user.id),
            record=validated_user_dict,
        )

    async def on_after_forgot_password(
        self, user: User, token: str, request: Optional[Request] = None
    ):
        # Never log the token: it grants a password reset. Deliver it to the
        # user out of band (e.g. email) instead.
        runtime.logger.info(f"Password reset requested for user {user.username}")

    async def on_after_request_verify(
        self, user: User, token: str, request: Optional[Request] = None
    ):
        # Never log the token: it grants email verification.
        runtime.logger.info(f"Email verification requested for user {user.username}")

    async def on_after_login(
        self,
        user: User,
        request: Optional[Request] = None,
        response: Optional[Response] = None,
    ) -> None:
        """
        After user login:
        1. Refresh the file-converter access token (editor+ roles)
        2. Authenticate the socket connection

        :param user: The user that is logging in
        :param request: Optional FastAPI request
        :param response: Optional response built by the transport.
        Defaults to None
        """
        # A successful login resets the per-account limiter so it only counts
        # failed attempts (the user's own logins must not consume the budget,
        # and bogus attempts against a known address must not outlast a real
        # sign-in). Keyed on the submitted form identifier, exactly as the
        # limiter keys it; request.form() is cached by Starlette, so re-reading
        # it here is free. Done before the sid early-return below so API-only
        # logins (SDK, scripts) also clear the counter.
        if request is not None:
            try:
                identifier = (await request.form()).get("username")
            except Exception:
                identifier = None
            if identifier:
                await clear_login_rate_limit(str(identifier))

        worker_pid = os.getpid()
        # Step 1: the file-converter token. Uploads 401 without it, and it
        # must exist however the user signs in - kept ahead of the socket
        # step, whose sid check returns early for API logins (SDK, scripts,
        # agent pairing).
        try:
            if user.role_id >= auth_settings.ROLE_ACCESS_LEVELS.get("editor"):
                await regenerate_access_token(user=user, service_name="file-converter")
        except Exception:
            runtime.logger.exception(
                f"Failed to refresh the file-converter token after login [Worker {worker_pid}]"
            )
        try:
            # Step 2: Socket authentication (web-app logins carry a socket sid)
            if request and response and "set-cookie" in response.headers:
                sid = request.headers.get("x-sid")
                if not sid:
                    # Routine for API-only logins (SDK, scripts): there is no
                    # socket session to authenticate
                    runtime.logger.info(
                        f"There is no sid in the request headers. User: {user.username} [Worker {worker_pid}]"
                    )
                    return

                cookie = response.headers["set-cookie"]
                jwt_token = cookie.split("mascope_auth=")[1].split(";")[0]

                # Authenticate the socket connection
                await authenticate_socket_connection(
                    sid=sid, token=jwt_token, minimum_role="guest"
                )
        except SocketUnauthenticatedError as e:
            runtime.logger.warning(
                f"Socket authentication failed after login: {str(e)} [Worker {worker_pid}]"
            )
        except Exception:
            runtime.logger.exception(
                f"Unexpected error during socket authentication after login [Worker {worker_pid}]"
            )
        return

    async def on_after_update(
        self,
        user: models.UP,
        update_dict: Dict[str, Any],
        request: Optional[Request] = None,
    ) -> None:
        """
        Perform logic after successful user update.

        :param user: The updated user
        :param update_dict: Dictionary with the updated user fields.
        :param request: Optional FastAPI request that
        triggered the operation, defaults to None.
        """
        runtime.logger.info(f"User `{user.username}` updated.")

        # Revoke access tokens if password changed
        if "password" in update_dict:
            runtime.logger.info(f"User `{user.username}` password was changed.")
            await delete_user_access_tokens(user_id=user.id)
            # Uploads need the file-converter token, and it is otherwise only
            # minted at login or on promotion to editor, so the wipe above would
            # leave editor+ users unable to upload until their next sign-in. SDK
            # and instrument-agent tokens stay revoked on purpose: those are
            # handed out explicitly and their holders re-pair.
            editor_level = auth_settings.ROLE_ACCESS_LEVELS.get("editor")
            if user.role_id is not None and user.role_id >= editor_level:
                await regenerate_access_token(user=user, service_name="file-converter")

        user_dict = await self._get_user_dict_with_role(user)
        validated_user_dict = UserRead.model_validate(user_dict).model_dump()

        # Broadcast to all clients for admin views
        await emit_record_updated(
            record_type="user", record_id=str(user.id), record=validated_user_dict
        )

        # Also emit to the specific user's room for their own profile updates
        await emit_record_updated(
            record_type="user_me",
            record_id=str(user.id),
            record=validated_user_dict,
            room=f"user-{user.id}",
        )
        return

    async def on_after_delete(
        self,
        user: User,
        request: Optional[Request] = None,
    ):
        """
        Perform logic after successful user delete.

        :param user: The deleted user
        """
        await emit_record_deleted(record_type="user", record_id=str(user.id))
