[project]
name = "mascope_match"
version = "0.0.0"
description = "Mascope's match computation library"
authors = [{ name = "Ultra Trace Systems Oy", email = "support@ultratrace.eu" }]
requires-python = ">=3.12,<3.13"
license.text = "Apache-2.0"
dependencies = [
    "mascope_runtime",
    "mascope_file",
    "mascope_chem",
    "mascope_signal",
    "numpy~=1.26",
    "pandas~=2.2",
    "scipy~=1.13",
    "xarray>=2026.7.0",
    "nanoid~=2.0.0",
    "pydantic>=2.13.4,<3",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13"]
build-backend = "uv_build"