[project]
name = "mascope_sdk"
version = "2026.7.7"
description = "Mascope's public SDK library, wrapping the app's REST API."
classifiers = [
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
authors = [
    { name = "Oskari Kausiala", email = "oskari.kausiala@ultratrace.eu" },
    { name = "Philip Chernonog" },
    { name = "Konstantin Tumashevich" },
    ]
maintainers = [
    { name = "Oskari Kausiala", email = "oskari.kausiala@ultratrace.eu" },
    ]
license.text = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.34.2,<3",
    "loguru>=0.7.3",
    "pandas>=2.0.0",
    "tqdm>=4.70.0",
    "python-dotenv>=1.0.0",
]

[project.urls]
homepage = "https://ultratrace.eu/"
repository = "https://github.com/ultra-trace-systems/mascope"
documentation = "https://github.com/ultra-trace-systems/mascope"
"Bug Tracker" = "https://github.com/ultra-trace-systems/mascope/issues"

[build-system]
requires = ["uv_build>=0.12.1,<0.13"]
build-backend = "uv_build"
