"""Tests: each operation declares the credentials the backend accepts on it.

fastapi-users declares every auth backend's scheme on every route that
authenticates, but ``get_enabled_backends`` takes an API token only on an
endpoint marked ``token_access`` (``api_route``, and the tus upload routes
``sample_files_routes`` stamps) and answers a token anywhere else with 401. The
document restates the token from that flag (``app/fast.py``), so an API client
or a generated client offers one exactly where it works.

Checked over every operation, with the expectation derived from each route's
own dependency tree rather than from the schemes FastAPI declared for it, so an
operation the rewrite fails to match - a parameterised path, a generated tus
route, a route authenticated some other way - fails here as well.
"""

import pytest
from fastapi.routing import iter_route_contexts

from mascope_backend.api.new.auth.backend import get_enabled_backends
from mascope_backend.app.fast import fast


#: An operation that takes the session cookie alone.
_COOKIE = [{"APIKeyCookie": []}]

#: An operation that also takes an API token, with the header naming its service.
_COOKIE_OR_TOKEN = [{"APIKeyCookie": []}, {"APIToken": [], "ServiceName": []}]


def _authenticates(route) -> bool:
    """
    Whether the route's credentials are chosen by ``get_enabled_backends``.

    :param route: A route context from ``iter_route_contexts``, whose dependant
        carries the dependencies of the routers it was included through.
    :return: ``True`` if the backend selector is anywhere in its dependency tree.
    """
    pending = [route.dependant]
    while pending:
        dependant = pending.pop()
        if dependant.call is get_enabled_backends:
            return True
        pending.extend(dependant.dependencies)
    return False


def _operations():
    """
    Every operation the app puts in its document.

    ``iter_route_contexts``, not ``fast.routes``: included routers stay nested
    there.

    :return: ``(path, method, route)`` per operation, the method lowercased as
        the document keys it.
    """
    for route in iter_route_contexts(fast.routes):
        if not route.methods or not getattr(route, "include_in_schema", False):
            continue
        for method in sorted(route.methods):
            yield route.path_format, method.lower(), route


def test_each_operation_offers_a_token_exactly_where_one_is_accepted():
    """An operation the backend selector guards offers the cookie, and a token
    only when its endpoint is token_access. Any other offers no token: nothing
    when it is public, the cookie alone when, like logout, it authenticates
    without the selector."""
    paths = fast.openapi()["paths"]
    checked = set()
    wrong = []
    for path, method, route in _operations():
        checked.add((path, method))
        declared = paths[path][method].get("security", [])
        if _authenticates(route):
            token_access = getattr(route.endpoint, "token_access", False)
            if declared != (_COOKIE_OR_TOKEN if token_access else _COOKIE):
                wrong.append(f"{method.upper()} {path} (token_access={token_access})")
        elif declared not in ([], _COOKIE):
            wrong.append(f"{method.upper()} {path} (not guarded by the selector)")

    documented = {(path, method) for path, ops in paths.items() for method in ops}
    assert checked == documented
    assert not wrong, "security does not match what the backend accepts:\n" + (
        "\n".join(wrong)
    )


@pytest.mark.parametrize(
    ("method", "path", "expected"),
    [
        # The SDK reads a sample's assignments with its token.
        ("get", "/api/peak-assignments/sample/{sample_item_id}", _COOKIE_OR_TOKEN),
        # Generated by tuspyserver, with the flag stamped on its endpoint.
        ("patch", "/api/sample/files/upload/tus/{uuid}", _COOKIE_OR_TOKEN),
        # The web app's own: a token sent here is refused.
        ("get", "/api/attribute_templates", _COOKIE),
        ("post", "/api/auth/login", []),
    ],
)
def test_known_operations_declare_their_credentials(method, path, expected):
    operation = fast.openapi()["paths"][path][method]
    assert operation.get("security", []) == expected
