"""Initial schema

Revision ID: be6a2a093ade
Revises:
Create Date: 2026-02-19 16:40:13.458115

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from mascope_backend.roles import ROLE_ACCESS_LEVELS


# The view as this migration created it, frozen here rather than taken from
# the live model: a migration has to describe the schema as it was, and the
# model's view SQL follows the model. Taken from the model, this step broke
# the moment a later migration added a column to the view - the SQL named a
# column that does not exist yet at this point of the chain, and every walk
# from an empty database failed here. Later migrations that change the view
# carry their own frozen copies the same way.
_SAMPLE_VIEW_SQL = """
    CREATE VIEW sample_view AS
    SELECT
        si.sample_item_id,
        sf.sample_file_id,
        sf.instrument_function_id,
        si.sample_batch_id,
        si.ionization_mode_id,
        si.sample_item_name,
        si.sample_item_type,
        si.locked,
        si.sample_item_attributes,
        si.filter_id,
        si.tic,
        si.polarity,
        si.t0,
        si.t1,
        si.sample_item_utc_created,
        si.sample_item_utc_modified,
        sf.filename,
        sf.instrument,
        sf.method_file,
        sf.length,
        sf.range,
        sf.mz_calibration,
        sf.datetime,
        sf.datetime_utc
    FROM sample_item si
    INNER JOIN sample_file sf ON si.sample_file_id = sf.sample_file_id;
"""


# revision identifiers, used by Alembic.
revision: str = "be6a2a093ade"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute_template",
        sa.Column("attribute_template_id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("template", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint(
            "attribute_template_id", name=op.f("pk_attribute_template")
        ),
    )
    op.create_table(
        "instrument_function",
        sa.Column("instrument_function_id", sa.String(length=32), nullable=False),
        sa.Column("instrument", sa.String(length=64), nullable=False),
        sa.Column("method_file", sa.String(length=512), nullable=False),
        sa.Column("datetime_utc", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("peakshape", sa.JSON(), nullable=True),
        sa.Column("resolution_function", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint(
            "instrument_function_id", name=op.f("pk_instrument_function")
        ),
    )
    op.create_table(
        "ionization_mechanism",
        sa.Column("ionization_mechanism_id", sa.String(length=16), nullable=False),
        sa.Column("ionization_mechanism_polarity", sa.String(length=1), nullable=False),
        sa.Column("ionization_mechanism", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint(
            "ionization_mechanism_id", name=op.f("pk_ionization_mechanism")
        ),
        sa.UniqueConstraint(
            "ionization_mechanism",
            name=op.f("uq_ionization_mechanism_ionization_mechanism"),
        ),
    )
    op.create_table(
        "role",
        sa.Column("role_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("role_id", name=op.f("pk_role")),
        sa.UniqueConstraint("role_name", name=op.f("uq_role_role_name")),
    )
    # Seed the fixed role rows (the canonical name -> access_level mapping).
    # These are reference data the app relies on, and first-owner registration
    # needs them present. Seeded in the initial schema so every fresh database
    # has them; existing databases already past this revision are unaffected.
    # ROLE_ACCESS_LEVELS lives in a secret-free module so it is safe to import
    # here (this migration runs in db_init, which has no JWT secret).
    op.bulk_insert(
        sa.table(
            "role",
            sa.column("role_id", sa.Integer),
            sa.column("role_name", sa.String),
        ),
        [
            {"role_id": level, "role_name": name}
            for name, level in ROLE_ACCESS_LEVELS.items()
        ],
    )
    op.create_table(
        "target_collection",
        sa.Column("target_collection_id", sa.String(length=16), nullable=False),
        sa.Column("target_collection_name", sa.String(length=256), nullable=False),
        sa.Column("target_collection_description", sa.Text(), nullable=True),
        sa.Column(
            "target_collection_type",
            sa.String(length=64),
            server_default=sa.text("'TARGETS'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "target_collection_id", name=op.f("pk_target_collection")
        ),
    )
    op.create_table(
        "target_compound",
        sa.Column("target_compound_id", sa.String(length=16), nullable=False),
        sa.Column("target_compound_name", sa.Text(), nullable=True),
        sa.Column("target_compound_formula", sa.String(length=256), nullable=False),
        sa.Column("cas_number", sa.String(length=12), nullable=True),
        sa.PrimaryKeyConstraint("target_compound_id", name=op.f("pk_target_compound")),
    )
    op.create_table(
        "workspace",
        sa.Column("workspace_id", sa.String(length=16), nullable=False),
        sa.Column("workspace_name", sa.String(length=256), nullable=False),
        sa.Column("workspace_description", sa.Text(), nullable=True),
        sa.Column(
            "workspace_type",
            sa.String(length=64),
            server_default=sa.text("'ANALYSIS'"),
            nullable=False,
        ),
        sa.Column(
            "locked", sa.Integer(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column("instrument", sa.String(length=64), nullable=True),
        sa.Column("icon", sa.JSON(), nullable=True),
        sa.Column("workspace_utc_created", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("workspace_utc_modified", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_workspace")),
    )
    op.create_table(
        "ionization_mode",
        sa.Column("ionization_mode_id", sa.String(length=16), nullable=False),
        sa.Column("ionization_mode_name", sa.String(length=256), nullable=False),
        sa.Column("ionization_mode_token", sa.String(length=256), nullable=True),
        sa.Column("ionization_mode_polarity", sa.String(length=1), nullable=False),
        sa.Column("ionization_mechanism_ids", sa.JSON(), nullable=False),
        sa.Column("calibration_collection_id", sa.String(length=16), nullable=True),
        sa.Column("diagnostic_collection_id", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(
            ["calibration_collection_id"],
            ["target_collection.target_collection_id"],
            name=op.f("fk_ionization_mode_calibration_collection_id_target_collection"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["diagnostic_collection_id"],
            ["target_collection.target_collection_id"],
            name=op.f("fk_ionization_mode_diagnostic_collection_id_target_collection"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("ionization_mode_id", name=op.f("pk_ionization_mode")),
        sa.UniqueConstraint(
            "ionization_mode_token",
            name=op.f("uq_ionization_mode_ionization_mode_token"),
        ),
    )
    op.create_table(
        "sample_batch",
        sa.Column("sample_batch_id", sa.String(length=16), nullable=False),
        sa.Column("workspace_id", sa.String(length=16), nullable=False),
        sa.Column("sample_batch_name", sa.String(length=256), nullable=False),
        sa.Column("sample_batch_description", sa.Text(), nullable=True),
        sa.Column(
            "sample_batch_type",
            sa.String(length=64),
            server_default=sa.text("'ANALYSIS'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'ready'"),
            nullable=False,
        ),
        sa.Column(
            "locked", sa.Integer(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column(
            "polarity",
            sa.String(length=4),
            server_default=sa.text("'+-'"),
            nullable=False,
        ),
        sa.Column(
            "sample_batch_utc_created", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "sample_batch_utc_modified", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.workspace_id"],
            name=op.f("fk_sample_batch_workspace_id_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sample_batch_id", name=op.f("pk_sample_batch")),
    )
    op.create_table(
        "sample_file",
        sa.Column("sample_file_id", sa.String(length=16), nullable=False),
        sa.Column("instrument_function_id", sa.String(length=32), nullable=True),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("instrument", sa.String(length=64), nullable=False),
        sa.Column("method_file", sa.String(length=512), nullable=True),
        sa.Column("datetime", sa.TIMESTAMP(), nullable=False),
        sa.Column("datetime_utc", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("length", sa.Float(), nullable=False),
        sa.Column("range", sa.JSON(), nullable=False),
        sa.Column("mz_calibration", sa.JSON(), nullable=True),
        sa.Column("polarity", sa.String(length=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_function_id"],
            ["instrument_function.instrument_function_id"],
            name=op.f("fk_sample_file_instrument_function_id_instrument_function"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("sample_file_id", name=op.f("pk_sample_file")),
        sa.UniqueConstraint("filename", name=op.f("uq_sample_file_filename")),
    )
    op.create_index(
        op.f("ix_sample_file_instrument_function_id"),
        "sample_file",
        ["instrument_function_id"],
        unique=False,
    )
    op.create_table(
        "target_compound_in_target_collection",
        sa.Column("target_compound_id", sa.String(length=16), nullable=False),
        sa.Column("target_collection_id", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_collection_id"],
            ["target_collection.target_collection_id"],
            name=op.f(
                "fk_target_compound_in_target_collection_target_collection_id_target_collection"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_compound_id"],
            ["target_compound.target_compound_id"],
            name=op.f(
                "fk_target_compound_in_target_collection_target_compound_id_target_compound"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "target_compound_id",
            "target_collection_id",
            name=op.f("pk_target_compound_in_target_collection"),
        ),
    )
    op.create_table(
        "target_ion",
        sa.Column("target_ion_id", sa.String(length=16), nullable=False),
        sa.Column("target_compound_id", sa.String(length=16), nullable=False),
        sa.Column("ionization_mechanism_id", sa.String(length=16), nullable=False),
        sa.Column("target_ion_formula", sa.String(length=256), nullable=False),
        sa.Column("filter_params", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ionization_mechanism_id"],
            ["ionization_mechanism.ionization_mechanism_id"],
            name=op.f("fk_target_ion_ionization_mechanism_id_ionization_mechanism"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_compound_id"],
            ["target_compound.target_compound_id"],
            name=op.f("fk_target_ion_target_compound_id_target_compound"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("target_ion_id", name=op.f("pk_target_ion")),
    )
    op.create_index(
        op.f("ix_target_ion_ionization_mechanism_id"),
        "target_ion",
        ["ionization_mechanism_id"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("registered_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.role_id"],
            name=op.f("fk_user_role_id_role"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "access_token",
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_access_token_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_access_token")),
    )
    op.create_index(
        op.f("ix_access_token_created_at"), "access_token", ["created_at"], unique=False
    )
    op.create_table(
        "sample_item",
        sa.Column("sample_item_id", sa.String(length=16), nullable=False),
        sa.Column("sample_batch_id", sa.String(length=16), nullable=False),
        sa.Column("sample_file_id", sa.String(length=16), nullable=False),
        sa.Column("sample_item_name", sa.String(length=256), nullable=False),
        sa.Column("sample_item_type", sa.String(length=64), nullable=False),
        sa.Column(
            "locked", sa.Integer(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column("sample_item_attributes", sa.JSON(), nullable=True),
        sa.Column("filter_id", sa.String(length=6), nullable=True),
        sa.Column("tic", sa.Float(), nullable=True),
        sa.Column("polarity", sa.String(length=1), nullable=True),
        sa.Column("ionization_mode_id", sa.String(length=16), nullable=True),
        sa.Column("t0", sa.Float(), nullable=True),
        sa.Column("t1", sa.Float(), nullable=True),
        sa.Column(
            "sample_item_utc_created", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "sample_item_utc_modified", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["ionization_mode_id"],
            ["ionization_mode.ionization_mode_id"],
            name=op.f("fk_sample_item_ionization_mode_id_ionization_mode"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sample_batch_id"],
            ["sample_batch.sample_batch_id"],
            name=op.f("fk_sample_item_sample_batch_id_sample_batch"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sample_file_id"],
            ["sample_file.sample_file_id"],
            name=op.f("fk_sample_item_sample_file_id_sample_file"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sample_item_id", name=op.f("pk_sample_item")),
    )
    op.create_index(
        op.f("ix_sample_item_sample_batch_id"),
        "sample_item",
        ["sample_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sample_item_sample_file_id"),
        "sample_item",
        ["sample_file_id"],
        unique=False,
    )
    op.create_table(
        "target_collection_in_sample_batch",
        sa.Column("target_collection_id", sa.String(length=16), nullable=False),
        sa.Column("sample_batch_id", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["sample_batch_id"],
            ["sample_batch.sample_batch_id"],
            name=op.f(
                "fk_target_collection_in_sample_batch_sample_batch_id_sample_batch"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_collection_id"],
            ["target_collection.target_collection_id"],
            name=op.f(
                "fk_target_collection_in_sample_batch_target_collection_id_target_collection"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "target_collection_id",
            "sample_batch_id",
            name=op.f("pk_target_collection_in_sample_batch"),
        ),
    )
    op.create_table(
        "target_isotope",
        sa.Column("target_isotope_id", sa.String(length=16), nullable=False),
        sa.Column("target_ion_id", sa.String(length=16), nullable=False),
        sa.Column("target_isotope_formula", sa.String(length=4096), nullable=False),
        sa.Column("mz", sa.Float(), nullable=False),
        sa.Column("relative_abundance", sa.Float(), nullable=False),
        sa.Column("resolution", sa.String(length=8), nullable=False),
        sa.CheckConstraint(
            "relative_abundance >= 0 AND relative_abundance <= 1",
            name=op.f("ck_target_isotope_relative_abundance_range"),
        ),
        sa.ForeignKeyConstraint(
            ["target_ion_id"],
            ["target_ion.target_ion_id"],
            name=op.f("fk_target_isotope_target_ion_id_target_ion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("target_isotope_id", name=op.f("pk_target_isotope")),
    )
    op.create_index(
        op.f("ix_target_isotope_target_ion_id"),
        "target_isotope",
        ["target_ion_id"],
        unique=False,
    )
    op.create_table(
        "match_collection",
        sa.Column("match_collection_id", sa.String(length=32), nullable=False),
        sa.Column("sample_item_id", sa.String(length=16), nullable=False),
        sa.Column("target_collection_id", sa.String(length=16), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("match_category", sa.Integer(), nullable=False),
        sa.Column("sample_peak_intensity_sum", sa.Float(), nullable=False),
        sa.Column(
            "match_collection_utc_created", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "match_collection_utc_modified", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.CheckConstraint(
            "match_category BETWEEN 0 AND 2",
            name=op.f("ck_match_collection_match_category_range"),
        ),
        sa.CheckConstraint(
            "match_score BETWEEN 0 AND 1",
            name=op.f("ck_match_collection_match_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["sample_item_id"],
            ["sample_item.sample_item_id"],
            name=op.f("fk_match_collection_sample_item_id_sample_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_collection_id"],
            ["target_collection.target_collection_id"],
            name=op.f("fk_match_collection_target_collection_id_target_collection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "match_collection_id", name=op.f("pk_match_collection")
        ),
    )
    op.create_index(
        op.f("ix_match_collection_sample_item_id"),
        "match_collection",
        ["sample_item_id"],
        unique=False,
    )
    op.create_table(
        "match_compound",
        sa.Column("match_compound_id", sa.String(length=32), nullable=False),
        sa.Column("sample_item_id", sa.String(length=16), nullable=False),
        sa.Column("target_compound_id", sa.String(length=16), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("match_category", sa.Integer(), nullable=False),
        sa.Column("sample_peak_intensity_sum", sa.Float(), nullable=False),
        sa.Column(
            "match_compound_utc_created", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "match_compound_utc_modified", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.CheckConstraint(
            "match_category BETWEEN 0 AND 2",
            name=op.f("ck_match_compound_match_category_range"),
        ),
        sa.CheckConstraint(
            "match_score BETWEEN 0 AND 1",
            name=op.f("ck_match_compound_match_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["sample_item_id"],
            ["sample_item.sample_item_id"],
            name=op.f("fk_match_compound_sample_item_id_sample_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_compound_id"],
            ["target_compound.target_compound_id"],
            name=op.f("fk_match_compound_target_compound_id_target_compound"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("match_compound_id", name=op.f("pk_match_compound")),
    )
    op.create_index(
        op.f("ix_match_compound_sample_item_id"),
        "match_compound",
        ["sample_item_id"],
        unique=False,
    )
    op.create_table(
        "match_ion",
        sa.Column("match_ion_id", sa.String(length=32), nullable=False),
        sa.Column("sample_item_id", sa.String(length=16), nullable=False),
        sa.Column("target_ion_id", sa.String(length=16), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("match_category", sa.Integer(), nullable=False),
        sa.Column("sample_peak_intensity_sum", sa.Float(), nullable=False),
        sa.Column("match_ion_utc_created", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("match_ion_utc_modified", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "match_category BETWEEN 0 AND 2",
            name=op.f("ck_match_ion_match_category_range"),
        ),
        sa.CheckConstraint(
            "match_score BETWEEN 0 AND 1", name=op.f("ck_match_ion_match_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["sample_item_id"],
            ["sample_item.sample_item_id"],
            name=op.f("fk_match_ion_sample_item_id_sample_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_ion_id"],
            ["target_ion.target_ion_id"],
            name=op.f("fk_match_ion_target_ion_id_target_ion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("match_ion_id", name=op.f("pk_match_ion")),
    )
    op.create_index(
        op.f("ix_match_ion_sample_item_id"),
        "match_ion",
        ["sample_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_ion_target_ion_id"), "match_ion", ["target_ion_id"], unique=False
    )
    op.create_table(
        "match_isotope",
        sa.Column("match_isotope_id", sa.String(length=32), nullable=False),
        sa.Column("target_isotope_id", sa.String(length=16), nullable=False),
        sa.Column("sample_item_id", sa.String(length=16), nullable=False),
        sa.Column("sample_peak_id", sa.String(length=20), nullable=False),
        sa.Column("sample_peak_mz", sa.Float(), nullable=False),
        sa.Column("sample_peak_intensity", sa.Float(), nullable=False),
        sa.Column("sample_peak_intensity_relative", sa.Float(), nullable=False),
        sa.Column("sample_peak_tof", sa.Float(), nullable=False),
        sa.Column("match_abundance_error", sa.Float(), nullable=False),
        sa.Column("match_mz_error", sa.Float(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column(
            "match_isotope_utc_created", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "match_isotope_utc_modified", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.CheckConstraint(
            "match_score BETWEEN 0 AND 1",
            name=op.f("ck_match_isotope_match_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["sample_item_id"],
            ["sample_item.sample_item_id"],
            name=op.f("fk_match_isotope_sample_item_id_sample_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_isotope_id"],
            ["target_isotope.target_isotope_id"],
            name=op.f("fk_match_isotope_target_isotope_id_target_isotope"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("match_isotope_id", name=op.f("pk_match_isotope")),
    )
    op.create_index(
        op.f("ix_match_isotope_sample_item_id"),
        "match_isotope",
        ["sample_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_isotope_sample_peak_id"),
        "match_isotope",
        ["sample_peak_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_isotope_target_isotope_id"),
        "match_isotope",
        ["target_isotope_id"],
        unique=False,
    )
    op.create_table(
        "match_rating",
        sa.Column("match_rating_id", sa.String(length=32), nullable=False),
        sa.Column("sample_item_id", sa.String(length=16), nullable=False),
        sa.Column("target_ion_id", sa.String(length=16), nullable=False),
        sa.Column(
            "match_rating_utc_created", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("checklist", sa.JSON(), nullable=True),
        sa.Column("environment", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "rating BETWEEN 0 AND 2", name=op.f("ck_match_rating_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["sample_item_id"],
            ["sample_item.sample_item_id"],
            name=op.f("fk_match_rating_sample_item_id_sample_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_ion_id"],
            ["target_ion.target_ion_id"],
            name=op.f("fk_match_rating_target_ion_id_target_ion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("match_rating_id", name=op.f("pk_match_rating")),
    )
    op.create_table(
        "match_sample",
        sa.Column("match_sample_id", sa.String(length=32), nullable=False),
        sa.Column("sample_item_id", sa.String(length=16), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("match_category", sa.Integer(), nullable=False),
        sa.Column("sample_peak_intensity_sum", sa.Float(), nullable=False),
        sa.Column(
            "match_sample_utc_created", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "match_sample_utc_modified", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.CheckConstraint(
            "match_category BETWEEN 0 AND 2",
            name=op.f("ck_match_sample_match_category_range"),
        ),
        sa.CheckConstraint(
            "match_score BETWEEN 0 AND 1",
            name=op.f("ck_match_sample_match_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["sample_item_id"],
            ["sample_item.sample_item_id"],
            name=op.f("fk_match_sample_sample_item_id_sample_item"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("match_sample_id", name=op.f("pk_match_sample")),
    )
    op.create_index(
        op.f("ix_match_sample_sample_item_id"),
        "match_sample",
        ["sample_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- Manually create sample_view, alembic cannot auto-detect database views  ---
    op.execute(_SAMPLE_VIEW_SQL)


def downgrade() -> None:
    """Downgrade schema."""

    # --- Manually drop sample_view BEFORE dropping tables  ---
    op.execute("DROP VIEW IF EXISTS sample_view")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_sample_sample_item_id"), table_name="match_sample")
    op.drop_table("match_sample")
    op.drop_table("match_rating")
    op.drop_index(
        op.f("ix_match_isotope_target_isotope_id"), table_name="match_isotope"
    )
    op.drop_index(op.f("ix_match_isotope_sample_peak_id"), table_name="match_isotope")
    op.drop_index(op.f("ix_match_isotope_sample_item_id"), table_name="match_isotope")
    op.drop_table("match_isotope")
    op.drop_index(op.f("ix_match_ion_target_ion_id"), table_name="match_ion")
    op.drop_index(op.f("ix_match_ion_sample_item_id"), table_name="match_ion")
    op.drop_table("match_ion")
    op.drop_index(op.f("ix_match_compound_sample_item_id"), table_name="match_compound")
    op.drop_table("match_compound")
    op.drop_index(
        op.f("ix_match_collection_sample_item_id"), table_name="match_collection"
    )
    op.drop_table("match_collection")
    op.drop_index(op.f("ix_target_isotope_target_ion_id"), table_name="target_isotope")
    op.drop_table("target_isotope")
    op.drop_table("target_collection_in_sample_batch")
    op.drop_index(op.f("ix_sample_item_sample_file_id"), table_name="sample_item")
    op.drop_index(op.f("ix_sample_item_sample_batch_id"), table_name="sample_item")
    op.drop_table("sample_item")
    op.drop_index(op.f("ix_access_token_created_at"), table_name="access_token")
    op.drop_table("access_token")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(
        op.f("ix_target_ion_ionization_mechanism_id"), table_name="target_ion"
    )
    op.drop_table("target_ion")
    op.drop_table("target_compound_in_target_collection")
    op.drop_index(
        op.f("ix_sample_file_instrument_function_id"), table_name="sample_file"
    )
    op.drop_table("sample_file")
    op.drop_table("sample_batch")
    op.drop_table("ionization_mode")
    op.drop_table("workspace")
    op.drop_table("target_compound")
    op.drop_table("target_collection")
    op.drop_table("role")
    op.drop_table("ionization_mechanism")
    op.drop_table("instrument_function")
    op.drop_table("attribute_template")
    # ### end Alembic commands ###
